### ISSUE TITLE
My blog doesn't appear to be showing in the feed

### ISSUE THREAD

**Issue by ghost** [planetpowershell/planetpowershell#121]
The feed link that I'm using is https://mattbobke.com/feed/atom but I also could be using https://mattbobke.com/feed/ from what I can see in other authors' files. Is there any way that I can troubleshoot this locally?

**Comment by kjacobsen** [comment]
Hi Matt,

I just saw your PR as well.

What issues are you seeing?

https://planetpowershell.com/logs might show up some more troubleshooting information if that helps.

**Comment by ghost** [comment]
Hi Kieran! My author info and blog aren't showing up on the website and feed, respectively. I thought it might be because of the link that I was providing since I see other authors with Wordpress blogs using the */feed/ URL instead of */feed/atom. Those logs only seem to be showing entries from the last couple of days, as well.

**Comment by Windos** [comment]
Rather than opening up an issue with the same title, I figured I'd comment on this one.

I'd thought my issue was the version of Ghost I was running... but in checking the logs link you posted above, [I can see](https://www.planetpowershell.com/logs/detail?id=c68c47d1-8475-4adf-b1eb-b3a404be6f71) that my old feed url is being queried. Is there a day of the week the site is rebuilt from the source files?

Cheers! (And thanks for your work on this site, @kjacobsen!)

**Comment by kjacobsen** [comment]
Hi,

Just took a quick look, seems builds were running but not the releases. Seems they stopped running from the end of April. I just checked and you are now both appearing.

Hopefully your sites should now start to appear correctly.

**Comment by ghost** [comment]
Thank you so much! I think we can close this issue. I really appreciate your work!
